server:
  port: 8089

spring:
  activemq:
    broker-url: 'tcp://localhost:61616'
    user: 'admin'
    password: 'admin'
    in-memory: false
    pool:
      enabled: false
  jms:
    cache:
      enabled: false

logging:
  level:
    root: info
